/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as ApiPublicDailyRemindersRouteImport } from './routes/api/public/daily-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyRemindersRoute = ApiPublicDailyRemindersRouteImport.update({
  id: '/api/public/daily-reminders',
  path: '/api/public/daily-reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/auth': typeof AuthRoute
  '/practice': typeof PracticeRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/syllabus': typeof SyllabusRoute
  '/api/public/daily-reminders': typeof ApiPublicDailyRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/auth': typeof AuthRoute
  '/practice': typeof PracticeRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/syllabus': typeof SyllabusRoute
  '/api/public/daily-reminders': typeof ApiPublicDailyRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-studio': typeof AiStudioRoute
  '/auth': typeof AuthRoute
  '/practice': typeof PracticeRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/syllabus': typeof SyllabusRoute
  '/api/public/daily-reminders': typeof ApiPublicDailyRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-studio'
    | '/auth'
    | '/practice'
    | '/scanner'
    | '/settings'
    | '/syllabus'
    | '/api/public/daily-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-studio'
    | '/auth'
    | '/practice'
    | '/scanner'
    | '/settings'
    | '/syllabus'
    | '/api/public/daily-reminders'
  id:
    | '__root__'
    | '/'
    | '/ai-studio'
    | '/auth'
    | '/practice'
    | '/scanner'
    | '/settings'
    | '/syllabus'
    | '/api/public/daily-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStudioRoute: typeof AiStudioRoute
  AuthRoute: typeof AuthRoute
  PracticeRoute: typeof PracticeRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SyllabusRoute: typeof SyllabusRoute
  ApiPublicDailyRemindersRoute: typeof ApiPublicDailyRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-reminders': {
      id: '/api/public/daily-reminders'
      path: '/api/public/daily-reminders'
      fullPath: '/api/public/daily-reminders'
      preLoaderRoute: typeof ApiPublicDailyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStudioRoute: AiStudioRoute,
  AuthRoute: AuthRoute,
  PracticeRoute: PracticeRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SyllabusRoute: SyllabusRoute,
  ApiPublicDailyRemindersRoute: ApiPublicDailyRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
